#!/usr/bin/env python
import logging
from wsgiref.simple_server import make_server
from framework.config import get_config
from framework.utils import get_router

config = get_config('server')

logging.basicConfig(
    level=config.get('logging', 'level'),
    format=config.get('logging', 'format', raw=True)
)
log = logging.getLogger(__file__)

app = get_router().make_wsgi_app()
log.info(
    'Initializing server instance at {0}:{1}'.format(
        config.get('http', 'host'), config.get('http', 'port')
    )
)
server = make_server(
    config.get('http', 'host'),
    config.getint('http', 'port'),
    app
)
log.info('Starting the server')
try:
    server.serve_forever()
except KeyboardInterrupt:
    log.info('Exitting on demand')
